export const STORE_MECHANICS = 'STORE_MECHANICS';
export const PREPARE_MECHANICS_STATUS = 'PREPARE_MECHANICS_STATUS';
export const STORE_MECHANICS_WITH_CARDS = 'STORE_MECHANICS_WITH_CARDS'
export const SELECT_MECHANIC = 'SELECT_MECHANIC'
export const STORE_SELECTED_CARDS = 'STORE_SELECTED_CARDS'